### ISSUE TITLE
# MVPS:

### ISSUE THREAD

**Issue by Evan-Leon** [dingtianding/Underhood#1]
- [x]  Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of     feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
- [x] MVPs are listed in an ordered list
- [x] Each MVP is broken down into bullet points

**Comment by Evan-Leon** [comment]
Hey Dean! Here are some suggested changes, let me know if you have any questions :)
- would consider turning search and pages into their own mvps (maybe taking away sidebar to leave for bonus) (so pages 5 and search 6)
- could you explain a little bit to me your idea for transfers & orders (i.e. the intended functionality)
- should specify which MVP will have full CRUD
  - transfers & orders would likely be good for this
- overall very well done!

**Comment by dingtianding** [comment]
Hi Evan, I've taken all the changes and made some update. See below for comments.

### would consider turning search and pages into their own mvps (maybe taking away sidebar to leave for bonus) (so pages 5 and search 6) 
Updated the MVP items

### could you explain a little bit to me your idea for transfers & orders (i.e. the intended functionality)
So transfer & orders are two aspects dealing with an account's fund/buying power:
a. Transfer would either 1. initiate a fund transfer from a bank account to deposit fund into user's account. 2. imitate a withdrawal to transfer from user's account out to a bank account. 
b. Order would be placed to either: 1. use the fund to buy a investment. 2. sell a investment to increase the fund.

### should specify which MVP will have full CRUD
### transfers & orders would likely be good for this
Updated under transfer & orders

**Comment by Evan-Leon** [comment]
Ok, cool, I think I am getting it now. 
so people can transfer in money, so that they have money to make orders with.
Orders will be them ordering stocks, from their funds they have transferred in.
Cool! That looks good to me, thank you for making those changes!
