### ISSUE TITLE
# Database Schema:

### ISSUE THREAD

**Issue by Evan-Leon** [dingtianding/Underhood#2]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table’s name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and back_ticked

**Comment by Evan-Leon** [comment]
Your schema looks great! 
My only question is on fund_transfer: 
-you make note of a wallet_id, what is this referencing, cash?
also please have each column title back-ticked as well
    Ex. `id`

**Comment by dingtianding** [comment]
1. Yes. It is referring to cash. I've updated 'cash' to be 'wallet' for clarity.
2. added back-ticks to all column names,

**Comment by moodln** [comment]
- [ ] Refer to [this page](https://github.com/appacademy/2021-11-29-NYC-Lecture-Notes/wiki/Schema) to see how the column names should be back-ticked :)

**Comment by dingtianding** [comment]
Thanks for the link. Updated to the correct "column names".
