### ISSUE TITLE
# Backend Routes

### ISSUE THREAD

**Issue by Evan-Leon** [dingtianding/Underhood#3]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in snake_case
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
- Ex. probably don't need a GET likes api endpoint because that info comes through the post show

**Comment by Evan-Leon** [comment]
Looks great, Dean! 
- my only note is on the DELETE for order. Maybe it would be better to make it a patch, so you can still have record of the order and maybe they don't sell their entire order

**Comment by dingtianding** [comment]
Interesting note. Thanks again!

1. Updated 'DELETE' TO BE 'PATCH' under `order`
